name: Run Backend Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd kanban-api
          pip install -r requirements.txt

      - name: Set Up Neon Tech Database URL
        run: |
          echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV

      - name: Debug Database Connection
        run: |
          echo "Testing Database Connection..."
          psql "${{ env.DATABASE_URL }}" -c "\dt"

      - name: Run Tests
        run: |
          cd kanban-api
          pytest tests --disable-warnings
